<br /><br />
<div id="view-content">
	<p>View script for controller <b>User</b> and script/action name <b>index</b></p>
</div>

<table width="500">
  <thead>
    <tr>
      <th>id</th>
      <th>username</th>
      <th>password</th>
      <th>level</th>
    </tr>
  </thead>
  <tbody>
  <?php foreach($this->data as $item){ ?>
    <tr>
      <td align="center"><?php echo $item['id'] ?></td>
      <td align="center"><?php echo $item['username'] ?></td>
      <td align="center"><?php echo $item['password'] ?></td>
      <?php if($item['level']==1){
        echo "<td align='center'>Admin</td>";
      }else {
        echo "<td align='center'>Member</td>"; ?>
     <?php } ?>

    </tr>
    <?php } ?>
  </tbody>
<?php
       echo $this->paginationControl($this->data, 'Sliding' , 'user/pagination.phtml');
?>
</table>

