<?php if ($this->pageCount): ?>
<div class="paginationControl" style="line-height: 30px;
border-bottom: 1px solid #989DA5;
border-top:1px solid #989DA5;">
<?php
    if (isset($this->previous)){
          echo '<a href="' . $this->url(array('page' => $this->previous)). '"> < Previous</a> | ';
    }
    foreach ($this->pagesInRange as $page){
       if ($page != $this->current){
               echo  '<a href="' . $this->url(array('page' => $page)). '">' . $page . '</a> | ';
      }else{
          echo $page . ' | ';
      }
   }
     if (isset($this->next)){
        echo '<a href="' . $this->url(array('page' => $this->next)) . '">Next ></a>';
       }
  ?>
</div>
<?php endif; ?>
